program : train.py
entity : recsys_04
method : bayes
metric:
  name: auc
  goal : minimize
parameters:
  embedding_dim : 
    values : [150,250,300,350,400,500]
  learning_rate: 
    values : [0.01, 0.005, 0.0001, 0.0005, 0.00001]
  num_layers : 
    values : [3,4,5,6]