wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1651494794
    t:
      1:
      - 5
      - 8
      - 53
      - 55
      2:
      - 5
      - 8
      - 53
      - 55
      3:
      - 24
      4: 3.8.5
      5: 0.12.14
      8:
      - 5
bagging_fraction:
  desc: null
  value: 0.4
bagging_freq:
  desc: null
  value: 2
feature_fraction:
  desc: null
  value: 0.8
learning_rate:
  desc: null
  value: 0.12981165253606822
num_leaves:
  desc: null
  value: 31
